Rewrite and improve update-initramfs

diff --git a/update-initramfs b/update-initramfs
--- a/update-initramfs
+++ b/update-initramfs
@@ -1,17 +1,15 @@
-#!/usr/bin/env bash
-if ((EUID != 0)); then
-    echo "This script should be run as root" >&2
-    exit 1
-fi
-
+#!/bin/sh
 if command -v limine-mkinitcpio >/dev/null 2>&1; then
-    limine-mkinitcpio
+	limine-mkinitcpio
 elif command -v mkinitcpio >/dev/null 2>&1; then
-    mkinitcpio -P
+	mkinitcpio --allpresets
+elif command -v limine-dracut >/dev/null 2>&1; then
+	limine-dracut
+elif command -v dracut >/dev/null 2>&1; then
+	dracut --regenerate-all --force
 elif command -v /usr/lib/booster/regenerate_images >/dev/null 2>&1; then
-    /usr/lib/booster/regenerate_images
-elif command -v dracut-rebuild >/dev/null 2>&1; then
-    dracut-rebuild
+	/usr/lib/booster/regenerate_images
 else
-    printf "\\033[31m The initramfs generator was not found, please update initramfs manually\\033[0m\\n"
+	echo 'Could not find a supported initramfs generator. Please regenerate your initramfs manually.'
+	exit 127
 fi
