Rewrite and improve update-initramfs (#21)
* Rewrite and improve update-initramfs

* update-initramfs: better detection of booster

* update-initramfs: don't try to be clever with the exit code

* update-initramfs: write error message to stderr

* update-initramfs: tab -> 4 spaces

* update-initramfs: re-add root check, change shell to bash

diff --git a/update-initramfs b/update-initramfs
--- a/update-initramfs
+++ b/update-initramfs
@@ -1,17 +1,20 @@
 #!/usr/bin/env bash
-if ((EUID != 0)); then
-    echo "This script should be run as root" >&2
+if (( EUID != 0 )); then
+    echo 'This script must be run as root.' >&2
     exit 1
 fi
 
 if command -v limine-mkinitcpio >/dev/null 2>&1; then
     limine-mkinitcpio
 elif command -v mkinitcpio >/dev/null 2>&1; then
-    mkinitcpio -P
-elif command -v /usr/lib/booster/regenerate_images >/dev/null 2>&1; then
+    mkinitcpio --allpresets
+elif command -v limine-dracut >/dev/null 2>&1; then
+    limine-dracut
+elif command -v dracut >/dev/null 2>&1; then
+    dracut --regenerate-all --force
+elif [[ -x /usr/lib/booster/regenerate_images ]]; then
     /usr/lib/booster/regenerate_images
-elif command -v dracut-rebuild >/dev/null 2>&1; then
-    dracut-rebuild
 else
-    printf "\\033[31m The initramfs generator was not found, please update initramfs manually\\033[0m\\n"
+    echo 'Could not find a supported initramfs generator. Please regenerate your initramfs manually.' >&2
+    exit 1
 fi
